# only works in latex environment
ifndef latex_varsall
  $(error latex_varsall is not set)
else
  $(info latex_varsall: $(latex_varsall))
endif

# default target
.PHONY: DEFAULT
DEFAULT:
    $(info this ran)
    $(warning $(latex_varsall))